name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Escolhe o ambiente de sua preferência (local, homlog, producao)'
        required: true
        default: 'http://localhost:3000'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          command: npx cross-env BASE_URL=${{ github.event.inputs.base_url }} npx cypress run
          browser: chrome
     
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
      
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
